### PR TITLE
Add merged TEPs table to README.md

### PR DESCRIPTION
**Pull request by v-lebedev**

### CODE REVIEW

**Comment by cumcum8197** [comment]
2023e5657c3e55930ac57ce0099e9901215a5bb8

**Comment by cumcum8197** [comment]
2023e5657c3e55930ac57ce0099e9901215a5bb8

**Comment by cumcum8197** [comment]
2023e5657c3e55930ac57ce0099e9901215a5bb8

**Comment by cumcum8197** [comment]
2023e5657c3e55930ac57ce0099e9901215a5bb8

**Comment by cumcum8197** [comment]
2023e5657c3e55930ac57ce0099e9901215a5bb8

**Review by opq0pqo — COMMENTED** [review]
@opq0pqo

**Pull request merged**
