### PR TITLE
Fix links in README

### PR DESCRIPTION
**Pull request by pyAndr3w**

### CODE REVIEW

**Review by hoseinrostamii — APPROVED** [review]

**Comment by cumcum8197** [comment]
1eaccb3057caa616331468981d8d3b0cf226da0f

**Comment by cumcum8197** [comment]
1eaccb3057caa616331468981d8d3b0cf226da0f

**Comment by cumcum8197** [comment]
1eaccb3057caa616331468981d8d3b0cf226da0f

**Comment by cumcum8197** [comment]
1eaccb3057caa616331468981d8d3b0cf226da0f

**Comment by cumcum8197** [comment]
1eaccb3057caa616331468981d8d3b0cf226da0f

**Pull request merged**
