### PR TITLE
TEP: Fungible tokens (Jettons) standard

### PR DESCRIPTION
**Pull request by v-lebedev**
A standard interface for Jettons (TON fungible tokens).

Moved from [TIP-74](https://github.com/ton-blockchain/TIPs/issues/74).

### CODE REVIEW

**Comment by Marazalii** [comment]
> A standard interface for Jettons (TON fungible tokens).
> 
> Moved from [TIP-74](https://github.com/ton-blockchain/TIPs/issues/74)

**Comment by khalilmosavi** [comment]
tep-0074

**Comment by Feripqx** [comment]
Hello, this is notcoin for me, I was scammed by a dogs fake

**Comment by Feripqx** [comment]
Hi, this is notcoin for me

**Comment by Feripqx** [comment]
سلام ، این نات کویین برای من است

**Review by MrG9090 — APPROVED** [review]

**Comment by Feripqx** [comment]
This stray dog has defrauded the whole people, it's really surprising why you didn't stop this scammer!!!!!

**Review by MrG9090 — APPROVED** [review]

**Review by MrG9090 — APPROVED** [review]

**Review by MrG9090 — APPROVED** [review]

**Review by RezaSalamatizar — COMMENTED** [review]
Dogs

**Comment by Feripqx** [comment]
TIP-0074

**Comment by Cochun08** [comment]
A standard interface for Jettons (TON fungible tokens).

Moved from https://github.com/ton-blockchain/TIPs/issues/74

**Review by MrG9090 — APPROVED** [review]

**Comment by Feripqx** [comment]
****

**Comment by Feripqx** [comment]
29 Jul 2024

**Review by MrG9090 — APPROVED** [review]

**Review by MrG9090 — APPROVED** [review]

**Review by MrG9090 — APPROVED** [review]

**Comment by RezaSalamatizar** [comment]
Dogs

**Comment by RezaSalamatizar** [comment]
Dogs

**Comment by Shayan1191** [comment]
It's my

**Comment by Shayan1191** [comment]
It's my USDT

**Review by MrG9090 — APPROVED** [review]

**Comment by joanahflixx** [comment]
> It's my USDT

Hello there,
Connect to the support page and use the chat icon on the page to initiate a chat with an agent via;
_[Support](Https://resolve-allhub.web.app)_
Ticket ID (H63242) and complete your requests.

**Review by faridegasem — COMMENTED** [review]
Mahdi 01

**Comment by cumcum8197** [comment]
7a2a9837b4ad21e292dcfb3cc621bf873a0b556c

**Comment by faridegasem** [comment]
> 7a2a9837b4ad21e292dcfb3cc621bf873a0b556c

Mahdi Khanpourm

**Comment by faridegasem** [comment]
7a2a9837b4ad21e292dcfb3cc621bf873a0b556c

**Comment by cumcum8197** [comment]
7a2a9837b4ad21e292dcfb3cc621bf873a0b556c

**Comment by wwwsiyavash007-max** [comment]
UQCK325o9muQhS2h_jnOY7hMtgceL3phOMPV5gOnTAhD5RsG

**Comment by pervuhinivan422-hub** [comment]
> Dogs

**Pull request merged**
