### PR TITLE
🔧 ABI

### PR DESCRIPTION
**Pull request by ex3ndr**
Draft of an ABI standard

### CODE REVIEW

**Comment by TrueCarry** [comment]
Getters have type, but what about getters that return tuples like get_nft_data, get_sale_data? Maybe instead of `type` it should be output: [BasicType]?
Also it would be great to have ABI represenation not only for methods/messages, but also for cells. In many cases cell layout is static and can be defined beforehand.

**Comment by ex3ndr** [comment]
Return types just a normal types. Right now it is just a struct in TACT and fields are mapped to tensor. So you define it as a normal struct/message

**Comment by andreypfau** [comment]
I have an extremely negative attitude to the idea of using JSON as an ABI for TON contracts in general. We have excellent ways to sterilize structures for cells - TLB and it is he who should be used as an ABI

**Comment by ex3ndr** [comment]
As always i see TF is fully delusional claming that we have "tlb" while in a YEAR no one was able to build a parser to any language. half of the parsing code in core is a manual parsing and not automated at all.

**Pull request closed without merging**
